apiVersion: apps/v1
kind: Deployment
metadata:
  name: sloth-cloud-api-lab
spec:
  template:
    spec:
      containers:
        - name: api
          envFrom:
            - configMapRef:
                name: sloth-cloud-api-lab-config
            - secretRef:
                name: sloth-cloud-api-lab-secrets
