apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sloth-labs
resources:
  - ../base
  - configmap.yaml
patches:
  - path: deployment-patch.yaml
images:
  - name: ghcr.io/replace-me/sloth-cloud-api-lab
    newName: sloth-cloud-api-lab
    newTag: dev
