apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sloth-cloud-api-lab
  labels:
    app.kubernetes.io/name: sloth-cloud-api-lab
    app.kubernetes.io/part-of: sloth-cloud-lab
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - sloth-cloud-api.lab.localhost
  rules:
    - backendRefs:
        - name: sloth-cloud-api-lab
          port: 80
