title: Sloth Platform Control
theme: dark
color: slate
headerStyle: clean
language: zh-Hans
target: _blank
quicklaunch:
  searchDescriptions: true
layout:
  Business Services:
    style: row
    columns: 2
  Platform:
    style: row
    columns: 2
