apiVersion: apps/v1
kind: Deployment
metadata:
  name: sloth-cloud-api
spec:
  template:
    spec:
      containers:
        - name: api
          envFrom:
            - configMapRef:
                name: sloth-cloud-api-config
            - secretRef:
                name: sloth-cloud-api-secrets
